### PR TITLE
couple small things I found

### PR DESCRIPTION
**Pull request by ahatch1490**

### CODE REVIEW

**Comment by ahatch1490** [comment]
So my PR is not good enough?

**Comment by tredfern** [comment]
I've been in Spokane. Haven't had time to take a look yet.

**Comment by ahatch1490** [comment]
Hey you want some me help refactoring the Web app piece? Or is your refactoring going to disrupt the api that it’s not worth it?

Also interested and n doing some rest api if you want

**Comment by tredfern** [comment]
I'm open to any refactoring on the web side of things. I don't have specifics yet on how any changes will impact the overall API. But, any impacts there should be manageable to consumers.

**Pull request merged**
